import Main from "@/components/layouts/Main";
import Heading from "@/components/ui/Heading";
import { classList } from "@/utils/tailwind";
import { ArrowBack } from "@mui/icons-material";
import { motion as m } from "framer-motion";
import type { ReactNode } from "react";
import { Link, useNavigate } from "react-router-dom";

type DisclaimerClause = {
  label: string;
  content: ReactNode;
  subclauses?: DisclaimerClause[];
};

type DisclaimerSubsection = {
  number: string;
  title: string;
  clauses: DisclaimerClause[];
};

type DisclaimerSection = {
  number: string;
  title: string;
  clauses?: DisclaimerClause[];
  subsections?: DisclaimerSubsection[];
};

const sections: DisclaimerSection[] = [
  {
    number: "1",
    title: "General",
    clauses: [
      {
        label: "(a)",
        content:
          "This platform and all current and future content, products and services offered by BlockPlanner Pty Ltd ACN 688 846 915 ABN 78 688 846 915 (BlockPlanner) on it, including all tools, calculators, reports and assessments (the Platform) are provided for general information purposes only.",
      },
      {
        label: "(b)",
        content:
          "Nothing on the Platform, whether paid or otherwise, constitutes professional advice of any kind, including but not limited to legal, financial, taxation, planning, engineering, architectural or property investment advice.",
      },
      {
        label: "(c)",
        content:
          "All reports, outputs, estimates, or results generated by the Platform are general in nature and based on publicly available information, third-party data, automated processes, and, where applicable, information provided by you. They are intended only as a starting point for you to undertake further queries and seek professional advice.",
      },
      {
        label: "(d)",
        content:
          "You should not rely on any report, output, estimate, or result generated by the Platform as a substitute for advice from a qualified professional who can assess your specific circumstances. This applies to all content, products and services on the Platform, now and in future, whether paid or made available without charge.",
      },
      {
        label: "(e)",
        content:
          "BlockPlanner recommends that you obtain independent professional advice before making any decision in connection with any property development, acquisition, investment or construction project. This includes verifying all planning controls, constraints, costs, charges and development potential with the relevant authorities and qualified professionals before acting on any information provided.",
      },
      {
        label: "(f)",
        content:
          "Where separate terms and conditions apply to a product or service on the Platform and those terms are inconsistent with this Disclaimer, those separate terms and conditions apply to the extent of the inconsistency.",
      },
    ],
  },
  {
    number: "2",
    title: "Products and Services",
    subsections: [
      {
        number: "2.1",
        title: "General",
        clauses: [
          {
            label: "(a)",
            content:
              "The products, services and tools, calculators, reports and assessments on the Platform:",
            subclauses: [
              {
                label: "(i)",
                content:
                  "do not assess the physical or legal conditions of any parcel of land or improvements; and",
              },
              {
                label: "(ii)",
                content:
                  "do not assess or contemplate existing improvements, quality of construction, building envelope, trees, easements, covenants, slope, heritage overlays, Crown lease conditions, servicing, or any other factor that may affect what can be built on, or done to, any parcel of land or improvements.",
              },
            ],
          },
          {
            label: "(b)",
            content:
              "BlockPlanner accepts no responsibility for any loss or damage arising from reliance on any products, services and tools, calculators, reports and assessments generated or made available on the Platform.",
          },
        ],
      },
      {
        number: "2.2",
        title: "Lease Variation Charges and Government Rebate Calculators",
        clauses: [
          {
            label: "(a)",
            content:
              "The Lease Variation Charge or development charge calculators and government rebate calculators available on the Platform are designed to provide indicative estimates only. The calculators do not assess or contemplate remissions, deferrals, concessions, or exemptions for which you may or may not be eligible.",
          },
          {
            label: "(b)",
            content:
              "Government charges, planning levies or charges, contributions, and rebates (including development application fees), and equivalent charges under any relevant law, regulation or disallowable instrument are subject to change at any time without notice.",
          },
          {
            label: "(c)",
            content:
              "Calculator outputs are based on publicly available data and assumptions that may not reflect the current rates, policies, or determinations of the ACT Government.",
          },
          {
            label: "(d)",
            content:
              "BlockPlanner does not warrant that any calculator output accurately reflects the charges, levies, or rebates that will be assessed or approved by the ACT Government or the relevant planning department or directorate in respect of a specific development or property.",
          },
          {
            label: "(e)",
            content:
              "You must verify all estimates directly with the ACT Government and any other relevant authority, department or statutory body before relying on them for any purpose, including financial modelling, feasibility assessment, or contract negotiations.",
          },
        ],
      },
      {
        number: "2.3",
        title: "Feasibility Assessments",
        clauses: [
          {
            label: "(a)",
            content:
              "Any feasibility assessments, financial projections, or development analysis generated by or through the Platform is indicative only and is based on inputs provided by you and general market assumptions.",
          },
          {
            label: "(b)",
            content:
              "Feasibility outputs do not constitute a financial product, financial advice, or a recommendation to proceed with any development or investment. They are not prepared by a licensed financial adviser and should not be treated as such.",
          },
          {
            label: "(c)",
            content:
              "Development feasibility is subject to a wide range of variables including, but not limited to, construction costs, financing costs, market conditions, planning approvals, government charges, and site-specific constraints. Actual outcomes may differ materially from any estimate or projection generated by the Platform.",
          },
          {
            label: "(d)",
            content:
              "BlockPlanner accepts no responsibility for any loss or damage arising from reliance on a feasibility assessment generated through the Platform.",
          },
        ],
      },
      {
        number: "2.4",
        title: "Costing, Design and Reporting Tools",
        clauses: [
          {
            label: "(a)",
            content:
              "The costing estimator, design and reporting tools available on the Platform are provided to assist users in exploring potential development options on parcels of land or the renovation of existing improvements. All outputs are preliminary and conceptual only.",
          },
          {
            label: "(b)",
            content:
              "Estimates are indicative only, are not quotes, and do not account for the specific condition of your property, the improvements or your eligibility for any rebate or incentive. Rebates and incentives are administered by third parties and change from time to time and without notice.",
          },
          {
            label: "(c)",
            content:
              "Design outputs do not constitute architectural drawings, engineering designs, or development applications, and do not represent compliance with any applicable planning scheme, building code or regulation, or Australian Standard.",
          },
          {
            label: "(d)",
            content:
              "You must verify all estimates directly with a qualified professional and/or third party offering the incentive or rebate.",
          },
          {
            label: "(e)",
            content:
              "Any design output must be reviewed and verified by a suitably qualified architect, building designer, or engineer before being used for any planning, construction, or regulatory purpose.",
          },
          {
            label: "(f)",
            content:
              "BlockPlanner makes no representation that any costing estimate is accurate or complete, or that any design output is suitable for lodgement with any planning authority or that it will satisfy the requirements of any applicable planning instrument, development control plan, or building regulation.",
          },
        ],
      },
      {
        number: "2.5",
        title: "Referral Tool",
        clauses: [
          {
            label: "(a)",
            content:
              "Any referral tool available on the Platform facilitates introductions between users and builders and tradespeople (the Referral Parties). BlockPlanner does not employ, engage, or supervise any Referral Party and is not a party to any agreement entered into between a user and a Referral Party.",
          },
          {
            label: "(b)",
            content:
              "BlockPlanner does not warrant or represent the qualifications, licensing, insurance, workmanship, reliability, or suitability of any Referral Party for any particular project or purpose.",
          },
          {
            label: "(c)",
            content:
              "It is your responsibility to independently verify that any Referral Party holds the licences, registrations, and insurances required by applicable law before engaging them for any work.",
          },
          {
            label: "(d)",
            content:
              "BlockPlanner accepts no liability for any loss, damage, delay, defect, or injury arising from or in connection with the acts or omissions of any Referral Party, or from any agreement entered into between you and a Referral Party.",
          },
          {
            label: "(e)",
            content:
              "Any dispute arising from an engagement with a Referral Party is a matter between you and that Referral Party. BlockPlanner is not obligated to assist in resolving any such dispute.",
          },
        ],
      },
    ],
  },
  {
    number: "3",
    title: "Accuracy and Currency",
    clauses: [
      {
        label: "(a)",
        content:
          "BlockPlanner takes reasonable care to ensure that data and information made available on or derived from the Platform is accurate and current at the time of publication. However, BlockPlanner does not warrant the accuracy, completeness, or currency of any information on the Platform.",
      },
      {
        label: "(b)",
        content:
          "Data and information on the Platform may be out of date at any given time. BlockPlanner is under no obligation to update any information and may change, remove, or add content at any time without notice.",
      },
      {
        label: "(c)",
        content:
          "You acknowledge that the tools, calculators, reports and assessments on the Platform are based on the laws, regulations and planning policies relevant to the Australian Capital Territory at the time of use and that those laws, regulations and planning policies are reviewed and amended regularly. BlockPlanner does not warrant the accuracy, completeness, or currency of any tools, calculators, reports and assessments on the Platform.",
      },
      {
        label: "(d)",
        content:
          "References to legislation, planning instruments, government policies, or regulatory requirements are provided for general guidance only and may not be accurate at the time of use. You should verify all such references with the relevant authority or a qualified professional.",
      },
    ],
  },
  {
    number: "4",
    title: "Limitation of Liability",
    clauses: [
      {
        label: "(a)",
        content:
          "You acknowledge that by accessing and using the Platform, you do so at your own risk. To the maximum extent permitted by law, BlockPlanner excludes all liability for any loss, damage, cost, or expense, whether direct, indirect, consequential, or otherwise, arising out of or in connection with:",
        subclauses: [
          {
            label: "(i)",
            content:
              "your use of, or reliance on, the Platform or any content, tool, calculator, assessment, result or report available on or derived from it.",
          },
          {
            label: "(ii)",
            content:
              "any error, omission, or inaccuracy of any content, tool, calculator, assessment, result or report available on or derived from it;",
          },
          {
            label: "(iii)",
            content:
              "any interruption, suspension or unavailability of the Platform;",
          },
          {
            label: "(iv)",
            content:
              "any engagement with Referral Parties introduced through the referral tool; and",
          },
          {
            label: "(v)",
            content:
              "any decision made in reliance on information, results or outputs from the Platform.",
          },
        ],
      },
      {
        label: "(b)",
        content:
          "Nothing in this Disclaimer excludes, restricts or modifies any right or remedy, or any guarantee, warranty, or other term or condition, implied or imposed by the Competition and Consumer Act 2010 (Cth), including the Australian Consumer Law, or any other applicable law that cannot be excluded or limited.",
      },
      {
        label: "(c)",
        content:
          "Where such non-excludable rights apply, BlockPlanner’s liability is limited, to the extent permitted by law, to resupplying the relevant service or paying the cost of having the service resupplied.",
      },
    ],
  },
  {
    number: "5",
    title: "Third-Party Links and Content",
    clauses: [
      {
        label: "(a)",
        content:
          "The Platform may incorporate or refer to data sourced from a third party or from publicly available data and material, or contain links to third-party websites or resources. BlockPlanner does not endorse or control such data, material and information or take responsibility for the content, accuracy, or availability of any third-party website or resource. Links are provided for convenience only.",
      },
      {
        label: "(b)",
        content:
          "Your use of any third-party website or resource is at your own risk and subject to the terms and conditions of that third party.",
      },
    ],
  },
  {
    number: "6",
    title: "Privacy",
    clauses: [
      {
        label: "(a)",
        content: (
          <>
            BlockPlanner collects and handles personal information in accordance
            with its Privacy Policy available here:{" "}
            <Link to="/privacy">Privacy Policy</Link>.
          </>
        ),
      },
      {
        label: "(b)",
        content:
          "By accessing and using the Platform, you consent to the collection and use of your personal information on the terms contained in the Privacy Policy.",
      },
    ],
  },
  {
    number: "7",
    title: "Governing law",
    clauses: [
      {
        label: "(a)",
        content:
          "This Disclaimer is governed by the laws of the Australian Capital Territory and you submit to the non-exclusive jurisdiction of the courts of the Australian Capital Territory.",
      },
    ],
  },
];

const ClauseList = ({
  clauses,
  nested = false,
}: {
  clauses: DisclaimerClause[];
  nested?: boolean;
}) => (
  <ol
    className={classList([
      "not-prose w-full min-w-0 list-none pl-0",
      nested ? "mt-4 space-y-3" : "mt-5 space-y-4",
    ])}
  >
    {clauses.map((clause, clauseIndex) => (
      <li
        key={clause.label + "-" + clauseIndex}
        className="grid min-w-0 grid-cols-[2.5rem_minmax(0,1fr)] gap-x-2 text-base leading-7 text-gray-700"
      >
        <span className="font-medium text-bp-blueGum">{clause.label}</span>
        <div className="min-w-0 break-words">
          <p className="m-0">{clause.content}</p>
          {clause.subclauses && (
            <ClauseList clauses={clause.subclauses} nested />
          )}
        </div>
      </li>
    ))}
  </ol>
);

export const DisclaimerPage = () => {
  const navigate = useNavigate();

  return (
    <Main>
      <section>
        <div className="relative mx-auto max-w-260">
          <m.button
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3, delay: 0.25, ease: "easeOut" }}
            className={classList([
              "flex align-middle gap-1",
              "text-sm font-medium",
              "underline decoration-transparent underline-offset-2",
              "hover:decoration-gray-700",
              "transition-colors duration-200",
              "px-2 py-1",
              "rounded-md",
            ])}
            onClick={() => navigate(-1)}
          >
            <ArrowBack fontSize="small" />
            Go Back
          </m.button>

          <m.div
            initial={{ y: 100 }}
            animate={{ y: 0 }}
            transition={{ duration: 0.4, ease: "easeOut" }}
            className="mt-4 min-w-0 overflow-hidden rounded-md bg-white p-6 shadow-lg md:px-16 md:pb-16 md:pt-10"
          >
            <Heading tag="h1" size="h1">
              Disclaimer
            </Heading>
            <div className="prose mt-6 max-w-none md:mt-10">
              {sections.map((section) => (
                <article
                  key={section.number}
                  className="min-w-0 mt-10 first:mt-0"
                >
                  <h2>
                    {section.number}. {section.title}
                  </h2>
                  {section.clauses && <ClauseList clauses={section.clauses} />}
                  {section.subsections?.map((subsection) => (
                    <section key={subsection.number} className="mt-8">
                      <h3>
                        {subsection.number}. {subsection.title}
                      </h3>
                      <ClauseList clauses={subsection.clauses} />
                    </section>
                  ))}
                </article>
              ))}
            </div>
          </m.div>
        </div>
      </section>
    </Main>
  );
};

export default DisclaimerPage;
